name: wlingo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bounceable: ^1.2.0
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.2.1
  flutter_svg: ^2.2.3
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  hooks_riverpod: ^3.2.1
  intl: ^0.20.2
  supabase_flutter: ^2.12.0
  shared_preferences: ^2.5.4
  dots_indicator: ^4.0.1
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  build_runner: ^2.11.1
  json_serializable: ^6.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - "assets/"
    - "assets/images/"
